name: "zlux-git-release"
description: "This action helps tag and merge zlux-release"
inputs:
  github-user:
    description: 'github user'
    required: false
  github-password:
    description: 'github password'
    required: false
  github-email:
    description: 'github email'
    required: false
  default-base:
    description: 'base branch to build from'
    required: false
  release-version:
    description: 'version of tags'
    required: false
  github-token:
    description: 'auth token'
    required: false
    
    

runs:
  using: "composite"
  steps:
    - name: 'process env vars'
      run: |
        # Sanitize envvars by (in order)
        # 1. remove comments (start with #); 
        # 2. remove blank lines
        sed '/^#/d' envvars.env | awk NF > envvars.env.new
        rm envvars.env
        mv envvars.env.new envvars.env
        cat envvars.env >> $GITHUB_ENV
      working-directory: ${{ github.action_path }}
      shell: bash
    
    - name: 'create release'
      run: |
        curl \
          -X POST \
          -H "Accept: application/vnd.github.v3+json" \
          -H "Authorization: token ${{ inputs.github-token }}" \
          https://api.github.com/repos/zowe/zss/merges \
          -d '{"base":"v1.x/master","head":"v1.x/rc","commit_message":"Relase"}'
      shell: bash