name: "Publish"
description: "This action helps publish zen"
inputs:
  os:
    description: 'os'
    required: true

runs:
  using: "composite"
  steps:
    - name: 'determine current branch or PR'
      run: |
        if [ -z ${{ github.event.pull_request.number }} ]
        then
          echo CURRENT_BRANCH=${GITHUB_REF#refs/heads/} >> $GITHUB_ENV
        else
          echo CURRENT_BRANCH=PR-${{ github.event.pull_request.number }} >> $GITHUB_ENV
        fi
      shell: bash
    - name: 'set version'
      run: |
        if [ -f "package.json" ]
        then
          ZEN_VERSION=$(cat package.json | grep version | head -1 | awk -F: '{ print $2 }' | sed 's/[",]//g' )
          echo "ZEN_VERSION=$ZEN_VERSION" | tr -d ' ' >> $GITHUB_ENV
        else
          echo 'package.json not found'
          exit 1
        fi
      shell: bash
    - name: 'set zen path'
      run: |
        echo REPOSITORY_NAME=$GITHUB_REPOSITORY | sed 's/zowe\///' >> $GITHUB_ENV
        echo WORKING_DIR=/home/runner/work/"$REPOSITORY_NAME" >> $GITHUB_ENV
      shell: bash
      
    - name: 'publish'
      run: |
        ARTIFACTORY_REPO=libs-snapshot-local/org/zowe
        TIMESTAMP=`date +%Y%m%d.%H%M%S`
        cd out/make
        if [ "${{ inputs.os }}" = "windows" ];
        then
          cd squirrel.windows/x64
          jfrog rt u zowe_enterprise_necessity-1.0.0-full.nupkg ${ARTIFACTORY_REPO}/${REPOSITORY_NAME}/${ZEN_VERSION}-{CURRENT_BRANCH}/zowe_enterprise_necessity-1.0.0-full.nupkg
          jfrog rt u zowe-enterprise-necessity-1.0.0\ Setup.exe ${ARTIFACTORY_REPO}/${REPOSITORY_NAME}/${ZEN_VERSION}-{CURRENT_BRANCH}/zowe-enterprise-necessity-1.0.0\ Setup.exe
        elif [ "${{ inputs.os }}" = "macos" ];
        then
          cd zip 
          ls 
        fi
        ls
      shell: bash