name: "prepare workflow"
description: "This action helps build zlux-core"
inputs:
  github-user:
    description: 'github user'
    required: false
  github-password:
    description: 'github password'
    required: false
  github-email:
    description: 'github email'
    required: false
  zowe-version:
    description: 'Version of release (X.X.X)'
    required: true

runs:
  using: "composite"
  steps:
    - name: 'process env vars'
      run: |
        # Sanitize envvars by (in order)
        # 1. remove comments (start with #); 
        # 2. remove blank lines
        sed '/^#/d' envvars.env | awk NF > envvars.env.new
        rm envvars.env
        mv envvars.env.new envvars.env
        cat envvars.env >> $GITHUB_ENV
      working-directory: ${{ github.action_path }}
      shell: bash
    
    - name: 'setup apt-get'
      run: |
        sudo apt-get update -y
        sudo apt-get install -y ant-contrib tart
      shell: bash
    
    - name: 'export github username and email'
      run: |
        if [ -n "${{ inputs.github-user }}" ]
        then
          git config --global user.name ${{ inputs.github-user }}
          echo GITHUB_USER=${{ inputs.github-user }} >> $GITHUB_ENV
        fi
        if [ -n "${{ inputs.github-email }}" ]
        then
          git config --global user.email ${{ inputs.github-email }}
        fi
        if [ -n "${{ inputs.github-password }}" ]
        then
          echo GITHUB_PASSWORD=${{ inputs.github-password }} >> $GITHUB_ENV
        fi
        echo GITHUB_REPOSITORY=${{ github.repository }} >> $GITHUB_ENV
        echo DEPLOY_BRANCH=$CURRENT_BRANCH | sed -e 's+\/+\-+' >> $GITHUB_ENV
      shell: bash
    
    - name: 'set Zowe version'
      run: |
        echo ZOWE_VERSION=${{ inputs.zowe-version }} >> $GITHUB_ENV
      shell: bash